// Generated by CoffeeScript 1.9.2
var chrono, moment, spanner;

moment = require('moment-timezone');

spanner = require('timespanner');

chrono = require('chronological');

moment = chrono(spanner(moment));

module.exports = {
  configuresaga: function(context) {
    context.map('weather update', function(e) {
      return 'daemon';
    });
    return context.ready();
  },
  oninstanceloaded: function(context) {
    context.every('weather update', function(e, cb) {
      context.settimeout('too long between updates', moment().add(5, 'seconds'));
      console.log(e);
      return cb();
    });
    context.every('too long between updates', function(e, cb) {
      console.log('It has been too long between updates, haha');
      return cb();
    });
    return context.ready();
  }
};
