// Generated by CoffeeScript 1.9.2
var chrono, moment, spanner;

moment = require('moment-timezone');

spanner = require('timespanner');

chrono = require('chronological');

moment = chrono(spanner(moment));

module.exports = {
  saga: function(context) {
    return context.ready();
  },
  instance: function(context) {
    return {
      'weather update': function(e, cb) {
        return cb('Not implemented');
      },
      'too long between updates': function(e, cb) {
        return cb('Not implemented');
      }
    };
  }
};
